[package]
name = "coccoc-tokenizer"
version = "1.0.0"
edition = "2024"
authors = ["Le Hoang Anh <lehoanganh.le2001@gmail.com>"]
repository = "https://github.com/anhle199/coccoc-tokenizer"
keywords = ["vietnamese", "vietnamese tokenizer", "segmenter", "tokenizer", "normalize", "language"]
categories = ["text-processing"]

[dependencies]
cxx = "1.0.186"

[build-dependencies]
cxx-build = "1.0.186"
